### ISSUE TITLE
It is support angular 11 version

### ISSUE THREAD

**Issue by gangasiddhi** [nikosanif/angular-authentication#6]

**Comment by gangasiddhi** [comment]
node_modules/@ngrx/effects/src/concat_latest_from.d.ts:2:145 - error TS2574: A rest element type must be an array type.

2 export declare function concatLatestFrom<T extends Observable<unknown>[], V>(observablesFactory: (value: V) => [...T]): OperatorFunction<V, [V, ...{
                                                                                                                                                  ~~~~
3     [i in keyof T]: ObservedValueOf<T[i]>;
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
4 }]>;

**Comment by gangasiddhi** [comment]
Error: src/app/authentication/services/auth.service.ts:49:17 - error TS2339: Property 'refreshTokenStatus' does not exist on type 'unknown'.

49           (auth.refreshTokenStatus === TokenStatus.INVALID) ||

**Comment by gangasiddhi** [comment]
am using @ngrx/store@11 and angular version 11

**Comment by nikosanif** [comment]
Hi @gangasiddhi! I am glad to see that this project is useful to the community and very willing to help you, but I am not sure that I understand your issue. Can you please be more descriptive and reform your issue by filling in the template of this issue?

**Comment by nikosanif** [comment]
Closed due to inactivity...
